baseURL = "https://snikumbh.github.io"
languageCode = "en-us"
title = "Sarvesh Nikumbh"
theme = "avicenna"
googleAnalytics = "UA-67848084-2"
timeout=3000


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/#about/"
    weight = 2
[[menu.main]]
    name = "Publications"
    url = "/#selpubs"
    weight = 3
[[menu.main]]
    name = "Education"
    url = "/#acads"
    weight = 4
[[menu.main]]
    name = "Experience"
    url = "/#profexp"
    weight = 6
[[menu.main]]
    name = "Awards"
    url = "/#awards"
    weight = 5


[params]
  subtitle= ""
  interests="Machine Learning, Data Science, Computational Biology"
  cv_name= ""
  blog=""
  fullpublist="https://scholar.google.co.uk/citations?hl=en&user=VIDJruYAAAAJ&view_op=list_works&sortby=pubdate"
  orcidId="0000-0003-3163-4447"
  publonsId="https://publons.com/researcher/1411651/sarvesh-nikumbh/"

[[params.affilation]]
  name = "Ex-MSD (Merck Sharp & Dohme), Visiting Researcher@Imperial College London & MRC LMS"
  position = "Open to work - Machine Learning, Data Science and/or Computational Biology roles"
  contact = "firstname [dot] lastname [at] gmail [dot] com (_remove spaces_)"


[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/snikumbh"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/sarveshnikumbh"

[[params.social]]
  name = "Google Scholar"
  icon = "book-open"
  url = "https://scholar.google.co.uk/citations?hl=en&user=VIDJruYAAAAJ&view_op=list_works&sortby=pubdate"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/sarveshnikumbh/"


[[params.introduction.paragraph]]
  text="""
Hi there, I am Sarvesh. I am a machine learning and data science researcher with ~15 years interdisciplinary research experience. I enjoy developing and applying interpretable and scalable machine learning methods to solve problems in diverse domains. So far I have worked in NLP and biology/health.   

Most recently, I was a Senior Research Scientist at MSD (Merck Sharp & Dohme) in the UK where I worked closely with neuroscientists on target identification, and on various other computational/data sciency aspects of the drug discovery pipeline. Before that I was a Postdoctoral Research Scientist at the Institute of Clinical Sciences, Faculty of Medicine, <a href="https://www.imperial.ac.uk/" target="_blank">Imperial College London</a> and <a href="https://lms.mrc.ac.uk/" target="_blank">MRC Laboratory of Medical Sciences (MRC LMS)</a>.

As a computational biologist, my general research interests are in machine learning methods, their interpretability and using them as tools towards understanding cellular biology better, more specifically, the regulatory aspects of the genome. Almost always, the choice of method and approach is governed by the roblem at hand. 

I did my PhD in Machine Learning and Computational Biology at the <a href="https://mpi-inf.mpg.de" target="_blank">Max Planck Institute for Informatics (MPI-INF)</a> and <a href="https://www.graduateschool-computerscience.de/" target="_blank">Saarland University</a>, Saarbrücken, Germany. My doctoral thesis was titled "Interpretable machine learning methods for prediction and analysis of genome regulation in 3D".

<ul class="flat">
<li><a href="https://orcid.org/0000-0003-3163-4447" target="_blank">ORCID</a></li>
<li><a href="https://publons.com/researcher/1411651/sarvesh-nikumbh/" target="_blank">Publons</a></li> 
</ul>

"""


[[params.publications]]
year="2024"

  [[params.publications.paper]]
    name = "Identification of transcription factor co-binding patterns with non-negative matrix factorization"
    authors = "Ieva Rauluseviciute, Timothée Launay, Guido Barzaghi, __Sarvesh Nikumbh__, Boris Lenhard, Arnaud Regis Krebs, Jaime A Castro-Mondragon, Anthony Mathelier"
    dest = "Nucleic Acids Research"
    link = "https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkae743/7747208"
    code_link = ""
    blog_link = ""
  

  [[params.publications.paper]]
    name = "Core promoterome of barley embryo"
    authors = "Simon Pavlu, __Sarvesh Nikumbh__, Martin Kovacik, Tadaichi An, Boris Lenhard, Hana Simkova, Pavla Navratilova"
    dest = "Computational and Structural Biotechnology Journal"
    link = "https://www.sciencedirect.com/science/article/pii/S2001037023004798"
    code_link = ""
    blog_link = ""
  

year="2023"

  [[params.publications.paper]]
    name = "Identifying promoter sequence architectures via a chunking-based algorithm using non-negative matrix factorisation"
    authors = "__Sarvesh Nikumbh__ and Boris Lenhard"
    dest = "PLoS Computational Biology"
    link = "https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1011491"
    code_link = "https://github.com/snikumbh/reproducible-seqArchR-manuscript"
    blog_link = ""


year="2017"

  [[params.publications.paper]]
    name = "All Fingers Are Not the Same: Handling Variable-Length Sequences in a Discriminative Setting Using Conformal Multi-Instance Kernels"
    authors = "__Sarvesh Nikumbh__, Peter Ebert and Nico Pfeifer"
    dest  = "Proceedings of the 17th International Workshop on Algorithms in Bioinformatics (WABI 2017)"
    link = "http://dx.doi.org/10.4230/LIPIcs.WABI.2017.16"
    code_link = ""
    blog_link = ""

  [[params.publications.paper]]
    name = "Genetic sequence-based prediction of long-range chromatin interactions suggests a potential role of short tandem repeat sequences in genome organization"
    authors = "__Sarvesh Nikumbh__ and Nico Pfeifer"
    dest  = "BMC Bioinformatics"
    link = "https://doi.org/10.1186/s12859-017-1624-x"
    code_link = ""
    blog_link = ""


[[params.academics]]
        [[params.academics.degree]]
                degree_name = "Ph.D. (Machine Learning & Computational Biology)"
                degree_year = ""
                degree_year_start = "2013"
                degree_year_end = "2019"
                degree_institution = "MPI for Informatics, Germany"
                degree_institution_url = "https://mpi-inf.mpg.de"
                degree_thesis_title = "Interpretable Machine Learning Methods for Prediction and Analysis of Genome Regulation in 3D"
                degree_description = ""

        [[params.academics.degree]]
                degree_name = "M.Tech. (Mathematical Modeling and Simulation)"
                degree_year_start = "2010"
                degree_year_end = "2012"
                degree_institution = "Centre for Modeling and Simulation, Savitribai Phule Pune University"
                degree_institution_url = "http://cms.unipune.ac.in/"
		degree_thesis_title = "Classification of Promoters by Chromatin Features"
                degree_description = ""

        [[params.academics.degree]]
                degree_name = "B.E. (Computer Engineering)"
                degree_year_start = "2004"
                degree_year_end = "2008"
                degree_institution = "St. Francis Institute of Technology, Mumbai University"
		degree_thesis_title = """<a href="https://arxiv.org/abs/1109.6838" target="_blank">Distributed Air Traffic Control: A Human Safety Perspective</a>"""
		degree_thesis_url = ""



[[params.awards]]
        [[params.awards.award]]
                award_name = "IMPRS-CS PhD Fellowship, MPI for Informatics"
                award_year = "2013"
                award_description = ""

        [[params.awards.award]]
                award_name = "Microsoft Research India Travel Grant"
                award_year = "2012"
                award_description = ""

        [[params.awards.award]]
                award_name = "Indian Association for Research in Computing Science (IARCS) Travel Grant"
                award_year = "2012"
                award_description = ""

        [[params.awards.award]]
                award_name = "Travel award by Dept. of Biotechnology, Govt. of India (Declined)"
                award_year = "2012"
                award_description = ""

        [[params.awards.award]]
                award_name = "Travel grant for 19th Machine Learning Summer School in La Palma, Spain"
                award_year = "2012"
                award_description = ""

        [[params.awards.award]]
                award_name = "French Government Scholarship"
                award_year = "2011"
                award_description = "Awarded by the French Ministry of Foreign Affairs for pursuing a summer internship at INRIA Grenoble"


[[params.news]]



[[params.experience]]
        [[params.experience.instance]]
                exp_title = "PhD Student/Researcher"
                exp_institution = "MPI for Informatics"
                exp_year_start = "2013"
                exp_year_end = "2019"

        [[params.experience.instance]]
                exp_title = "Statistical Consultant (remote; as free lancer)"
                exp_institution = "OpenAnalytics, Belgium"
                exp_year_start = "2012"
                exp_year_end = "2012"

        [[params.experience.instance]]
                exp_title = "Project Intern"
                exp_institution = "National Chemical Laboratory, Pune, India"
                exp_year_start = "2012"
                exp_year_end = "2012"

        [[params.experience.instance]]
                exp_title = "Summer Research Intern"
                exp_institution = "INRIA Rhône-Alpes, Grenoble, France"
                exp_year_start = "2011"
                exp_year_end = "2011"

        [[params.experience.instance]]
                exp_title = "Project Engineer"
                exp_institution = "Centre for Development of Advanced Computing, Mumbai, India"
                exp_year_start = "2008"
                exp_year_end = "2010"


